### PR TITLE
fix #62, adds local storage check to all bid form requests

### LINKED ISSUE #62: Form request getting 404 - blowing up github css
Steps to reproduce:
1) Go to an issue with a link withing github (https://github.com/codesy/codesy/issues/33)
2) Click on the link
3) Press backspace (to trigger popstate event)
4) Wait for it...

Expected:
Form should load without changing gitthub issue 

Result:
Form eventually loads but the layout of the github issue is destroyed.

I suspect this is a race condition between the content script loading the correct domain and the popstate event firing the request.

### PR DESCRIPTION
**Pull request by jdungan**
#62 was caused when codesy.url was not set.  This would cause a bid request against the github url and return a 404 that the extension attempted to append (very ugly).   The fix is to add a local storage check in the newpage funciton.

The will still be an error if the user happens to have the extension install with out getting a token set.  This should be worked out when fixing #25.

### CODE REVIEW

File: src/codesy.coffee [hunk 1]
```diff
@@ -48,38 +49,45 @@ codesy.appendForm = (form_html) ->
...
-  if changes.domains.newValue[0].domain isnt codesy.url
+  console.log "codesy: token changed"
+  if changes.domains.newValue[0].domain
     codesy.setDomain(changes.domains.newValue[0])
 
 chrome.runtime.onMessage.addListener (msg, sender, sendResponse)->
   console.log "codesy: xhr received"
   if msg.url
-    codesy.newpage()
+      codesy.newpage()
```
Comment (groovecoder) [inline src/codesy.coffee]: just whitespace difference? seems to make it inconsistent with the 2-space indents used everywhere else?

Comment (jdungan) [inline src/codesy.coffee]: an interrum fix was to put the local storage function here,  No functional change, but it does need to be cleaned up.

**Comment by groovecoder** [comment]
Just the nit-pick about the consistent spacing for the indentation. The rest looks and works well.
